### ISSUE TITLE
Failed to install from Brew

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast-cli#2]
09:38 $ brew install https://raw.githubusercontent.com/bilalyasar/homebrew/master/Library/Formula/hazelcast-cli.rb

```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
carrot2              gifcap               gtk-chtheme          source-to-image      todoman
easy-tag             gobby                klavaro              tarsnap-gui
geeqie               gsmartcontrol        orc-tools            terminator
==> Updated Formulae
afl-fuzz                  euca2ools                 lean-cli                  pushpin
apktool                   extract_url               libev                     qemu
apt-dater                 fftw                      libvirt                   sbcl
aws-sdk-cpp               freeswitch                mariadb                   sops
buku                      gcal                      mcabber                   svtplay-dl
cadubi                    gdb                       mkvtoolnix                swift
collectd                  git-tracker               neofetch                  swiftformat
crystal-lang              giter8                    no-more-secrets           swiftlint
dar                       gitlab-ci-multi-runner    nodeenv                   tcpkali
dependency-check          gmime                     open-mesh                 terragrunt
dmd                       gtk+                      open-ocd                  unrar
docker                    imagemagick               opus                      vim
docker-swarm              imagemagick@6             packer                    wavpack
dockward                  innotop                   parallel                  yle-dl
ejabberd                  jenkins                   pre-commit                youtube-dl
etcd                      kobalt                    pulseaudio                zimg
==> Renamed Formulae
eigen32 -> eigen@3.2
==> Deleted Formulae
dynamodb-local


curl: (22) The requested URL returned error: 404 Not Found
Error: Failure while executing: /usr/bin/curl --remote-time --location --user-agent Homebrew/1.1.7\ (Macintosh;\ Intel\ macOS\ 10.11.6)\ curl/7.43.0 --progress-bar --fail https://raw.githubusercontent.com/bilalyasar/homebrew/master/Library/Formula/hazelcast-cli.rb -o /Users/davidbrimley/Library/Caches/Homebrew/Formula/hazelcast-cli.rb
```

**Comment by sangaf** [comment]
same here

brew install -vd https://raw.githubusercontent.com/bilalyasar/homebrew/master/Library/Formula/hazelcast-cli.rb
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/0.9.9 (Macintosh; Intel Mac OS X 10.11.6) curl/7.43.0 https://raw.githubusercontent.com/bilalyasar/homebrew/master/Library/Formula/hazelcast-cli.rb -o /Users/sanjida.gafur/Library/Caches/Homebrew/Formula/hazelcast-cli.rb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
Error: Failure while executing: /usr/bin/curl --fail --remote-time --location --user-agent Homebrew/0.9.9\ (Macintosh;\ Intel\ Mac\ OS\ X\ 10.11.6)\ curl/7.43.0 https://raw.githubusercontent.com/bilalyasar/homebrew/master/Library/Formula/hazelcast-cli.rb -o /Users/sanjida.gafur/Library/Caches/Homebrew/Formula/hazelcast-cli.rb
/usr/local/Library/Homebrew/utils.rb:300:in `safe_system'
/usr/local/Library/Homebrew/utils/curl.rb:19:in `curl'
/usr/local/Library/Homebrew/formulary.rb:145:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:78:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:215:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:18:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:101:in `install'
/usr/local/Library/Homebrew/brew.rb:87:in `<main>'
